### ISSUE TITLE
[DEV-9] Fix Stylelint issues in style.css

### ISSUE THREAD

**Issue by DeineStrainReviewsDev** [DeineStrainReviewsDev/Tutorial#5]
**Jira Issue:** [DEV-9](https://deinestrainreviews.atlassian.net/browse/DEV-9)

# 🛠️ CSS Stylelint Issues Report

## 📌 Summary
This issue tracks multiple **Stylelint violations** detected in `style.css`. Each problem is documented below with an explanation and a suggested fix.

---

## ⚠️ **1. Unknown Rule: `scss_function-disallowed-list`**
- **Issue:** `Unknown rule scss_function-disallowed-list. Did you mean function-disallowed-list?`
- **Location:** `style.css` (Line 1)
- **Fix:** Replace `scss_function-disallowed-list` with `function-disallowed-list`.

---

## 🎨 **2. Modern Color Function Notation Required (`color-function-notation`)**
- **Issue:** Expected modern color-function notation (e.g., `rgb(0 0 0 / 0.2)` instead of `rgb(0, 0, 0, 0.2)`)  
- **Location:** `style.css` (Lines 14-18)  
- **Fix:** Use the **comma-free modern notation** for color functions.

**❌ Incorrect:**
```css
color: rgba(12, 122, 231, 0.2);
```
**✅ Correct:**
```css
color: rgb(12 122 231 / 0.2);
```

---

## 🎭 **3. Class Selector Must Use Kebab-Case (`selector-class-pattern`)**
- **Issue:** Expected class selector `.Test3` to be kebab-case (`.test3`)  
- **Location:** `style.css` (Line 71)  
- **Fix:** Rename `.Test3` to `.test3`.

**❌ Incorrect:**
```css
.navigation .Test3 {
  background-color: var(--accent-color);
}
```
**✅ Correct:**
```css
.navigation .test3 {
  background-color: var(--accent-color);
}
```

---

## 🌫️ **4. Alpha Value Must Use Percentage (`alpha-value-notation`)**
- **Issue:** Expected `0.15` to be `15%`  
- **Location:** `style.css` (Line 89)  
- **Fix:** Convert alpha values from decimal to percentage notation.

**❌ Incorrect:**
```css
box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
```
**✅ Correct:**
```css
box-shadow: 0 10px 25px rgba(0, 0, 0, 15%);
```

---

## 🎨 **5. Hex Colors Should Use Short Notation (`color-hex-length`)**
- **Issue:** Expected `#ffffff` to be `#fff`  
- **Location:** `style.css` (Line 15)  
- **Fix:** Convert long hex colors to short notation where possible.

**❌ Incorrect:**
```css
--white: #ffffff;
```
**✅ Correct:**
```css
--white: #fff;
```

---

## 📏 **6. Use Context Notation for Media Queries (`media-feature-range-notation`)**
- **Issue:** Expected `"min-width: 1200px"` to be `"width >= 1200px"`  
- **Location:** `style.css` (Lines 164, 194)  
- **Fix:** Use **context notation** (`width >=`) instead of **prefix notation** (`min-width:`).

**❌ Incorrect:**
```css
@media (min-width: 1200px) {
  body { padding: 30px 50px; }
}
```
**✅ Correct:**
```css
@media (width >= 1200px) {
  body { padding: 30px 50px; }
}
```

---

## 📄 **7. Empty Line Required Before Rules (`rule-empty-line-before`)**
- **Issue:** Expected an empty line before rule.  
- **Location:** `style.css` (Line 223)  
- **Fix:** Add an empty line before CSS rules.

**❌ Incorrect:**
```css
.container-right:hover {
  transform: translateY(-5px);
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}
```
**✅ Correct:**
```css
.container-right:hover {

  transform: translateY(-5px);
  box-shadow: 0 10px 25px rgba(0, 0, 0, 0.15);
}
```

---

## ✅ **Next Steps**
- [ ] Fix all identified issues in `style.css`
- [ ] Run `npx stylelint style.css --fix` to auto-fix minor errors
- [ ] Push a new commit with the fixes
- [ ] Ensure no new Stylelint warnings appear in the pipeline

---

### **📝 Notes**
- Stylelint rules help enforce **consistent code formatting and best practices**.
- Some issues can be **automatically fixed** using:
  ```bash
  npx stylelint --fix style.css
  ```
- Others require **manual renaming** of class selectors, variables, or function calls.

📢 **If you have questions, feel free to comment!** 🚀

[DEV-9]: https://deinestrainreviews.atlassian.net/browse/DEV-9?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
